# GNU Make project makefile autogenerated by Premake
ifndef config
  config=release32
endif

ifndef verbose
  SILENT = @
endif

ifndef CC
  CC = gcc
endif

ifndef CXX
  CXX = g++
endif

ifndef AR
  AR = ar
endif

ifeq ($(config),release32)
  OBJDIR     = ../build/x32/Release/PocoNet
  TARGETDIR  = ../bin
  TARGET     = $(TARGETDIR)/libPocoNet.a
  DEFINES   += -DNDEBUG -D_WIN32 -DWINVER=0x500 -DPOCO_NO_FPENVIRONMENT -DPCRE_STATIC -DPOCO_THREAD_STACK_SIZE -DFoundation_Config_INCLUDED -DMINGW32
  INCLUDES  += -I../Foundation/include -Iinclude -I../Util/include -I../XML/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -m32 -L/usr/lib32 -L../bin
  LIBS      += -lPocoUtil -lPocoXML -lPocoFoundation -liphlpapi -lws2_32 -lgdi32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../bin/libPocoUtil.a ../bin/libPocoXML.a ../bin/libPocoFoundation.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug32)
  OBJDIR     = ../build/x32/Debug/PocoNet
  TARGETDIR  = ../bin/debug
  TARGET     = $(TARGETDIR)/libPocoNet.a
  DEFINES   += -D_DEBUG -DDEBUG -D_WIN32 -DWINVER=0x500 -DPOCO_NO_FPENVIRONMENT -DPCRE_STATIC -DPOCO_THREAD_STACK_SIZE -DFoundation_Config_INCLUDED -DMINGW32
  INCLUDES  += -I../Foundation/include -Iinclude -I../Util/include -I../XML/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m32
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m32 -L/usr/lib32 -L../bin/debug
  LIBS      += -lPocoUtil -lPocoXML -lPocoFoundation -liphlpapi -lws2_32 -lgdi32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../bin/debug/libPocoUtil.a ../bin/debug/libPocoXML.a ../bin/debug/libPocoFoundation.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),release64)
  OBJDIR     = ../build/x64/Release/PocoNet
  TARGETDIR  = ../bin
  TARGET     = $(TARGETDIR)/libPocoNet.a
  DEFINES   += -DNDEBUG -D_WIN32 -DWINVER=0x500 -DPOCO_NO_FPENVIRONMENT -DPCRE_STATIC -DPOCO_THREAD_STACK_SIZE -DFoundation_Config_INCLUDED -DMINGW32
  INCLUDES  += -I../Foundation/include -Iinclude -I../Util/include -I../XML/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -O2 -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -s -m64 -L/usr/lib64 -L../bin
  LIBS      += -lPocoUtil -lPocoXML -lPocoFoundation -liphlpapi -lws2_32 -lgdi32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../bin/libPocoUtil.a ../bin/libPocoXML.a ../bin/libPocoFoundation.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

ifeq ($(config),debug64)
  OBJDIR     = ../build/x64/Debug/PocoNet
  TARGETDIR  = ../bin/debug
  TARGET     = $(TARGETDIR)/libPocoNet.a
  DEFINES   += -D_DEBUG -DDEBUG -D_WIN32 -DWINVER=0x500 -DPOCO_NO_FPENVIRONMENT -DPCRE_STATIC -DPOCO_THREAD_STACK_SIZE -DFoundation_Config_INCLUDED -DMINGW32
  INCLUDES  += -I../Foundation/include -Iinclude -I../Util/include -I../XML/include
  CPPFLAGS  += -MMD -MP $(DEFINES) $(INCLUDES)
  CFLAGS    += $(CPPFLAGS) $(ARCH) -g -m64
  CXXFLAGS  += $(CFLAGS) 
  LDFLAGS   += -m64 -L/usr/lib64 -L../bin/debug
  LIBS      += -lPocoUtil -lPocoXML -lPocoFoundation -liphlpapi -lws2_32 -lgdi32
  RESFLAGS  += $(DEFINES) $(INCLUDES) 
  LDDEPS    += ../bin/debug/libPocoUtil.a ../bin/debug/libPocoXML.a ../bin/debug/libPocoFoundation.a
  LINKCMD    = $(AR) -rcs $(TARGET) $(OBJECTS)
  define PREBUILDCMDS
  endef
  define PRELINKCMDS
  endef
  define POSTBUILDCMDS
  endef
endif

OBJECTS := \
	$(OBJDIR)/AbstractHTTPRequestHandler.o \
	$(OBJDIR)/DatagramSocket.o \
	$(OBJDIR)/DatagramSocketImpl.o \
	$(OBJDIR)/DialogSocket.o \
	$(OBJDIR)/DNS.o \
	$(OBJDIR)/FilePartSource.o \
	$(OBJDIR)/FTPClientSession.o \
	$(OBJDIR)/FTPStreamFactory.o \
	$(OBJDIR)/HostEntry.o \
	$(OBJDIR)/HTMLForm.o \
	$(OBJDIR)/HTTPAuthenticationParams.o \
	$(OBJDIR)/HTTPBasicCredentials.o \
	$(OBJDIR)/HTTPBufferAllocator.o \
	$(OBJDIR)/HTTPChunkedStream.o \
	$(OBJDIR)/HTTPClientSession.o \
	$(OBJDIR)/HTTPCookie.o \
	$(OBJDIR)/HTTPCredentials.o \
	$(OBJDIR)/HTTPDigestCredentials.o \
	$(OBJDIR)/HTTPFixedLengthStream.o \
	$(OBJDIR)/HTTPHeaderStream.o \
	$(OBJDIR)/HTTPIOStream.o \
	$(OBJDIR)/HTTPMessage.o \
	$(OBJDIR)/HTTPRequest.o \
	$(OBJDIR)/HTTPRequestHandler.o \
	$(OBJDIR)/HTTPRequestHandlerFactory.o \
	$(OBJDIR)/HTTPResponse.o \
	$(OBJDIR)/HTTPServer.o \
	$(OBJDIR)/HTTPServerConnection.o \
	$(OBJDIR)/HTTPServerConnectionFactory.o \
	$(OBJDIR)/HTTPServerParams.o \
	$(OBJDIR)/HTTPServerRequest.o \
	$(OBJDIR)/HTTPServerRequestImpl.o \
	$(OBJDIR)/HTTPServerResponse.o \
	$(OBJDIR)/HTTPServerResponseImpl.o \
	$(OBJDIR)/HTTPServerSession.o \
	$(OBJDIR)/HTTPSession.o \
	$(OBJDIR)/HTTPSessionFactory.o \
	$(OBJDIR)/HTTPSessionInstantiator.o \
	$(OBJDIR)/HTTPStream.o \
	$(OBJDIR)/HTTPStreamFactory.o \
	$(OBJDIR)/ICMPClient.o \
	$(OBJDIR)/ICMPEventArgs.o \
	$(OBJDIR)/ICMPPacket.o \
	$(OBJDIR)/ICMPPacketImpl.o \
	$(OBJDIR)/ICMPSocket.o \
	$(OBJDIR)/ICMPSocketImpl.o \
	$(OBJDIR)/ICMPv4PacketImpl.o \
	$(OBJDIR)/IPAddress.o \
	$(OBJDIR)/MailMessage.o \
	$(OBJDIR)/MailRecipient.o \
	$(OBJDIR)/MailStream.o \
	$(OBJDIR)/MediaType.o \
	$(OBJDIR)/MessageHeader.o \
	$(OBJDIR)/MulticastSocket.o \
	$(OBJDIR)/MultipartReader.o \
	$(OBJDIR)/MultipartWriter.o \
	$(OBJDIR)/NameValueCollection.o \
	$(OBJDIR)/NetException.o \
	$(OBJDIR)/NetworkInterface.o \
	$(OBJDIR)/NullPartHandler.o \
	$(OBJDIR)/PartHandler.o \
	$(OBJDIR)/PartSource.o \
	$(OBJDIR)/POP3ClientSession.o \
	$(OBJDIR)/QuotedPrintableDecoder.o \
	$(OBJDIR)/QuotedPrintableEncoder.o \
	$(OBJDIR)/RawSocket.o \
	$(OBJDIR)/RawSocketImpl.o \
	$(OBJDIR)/RemoteSyslogChannel.o \
	$(OBJDIR)/RemoteSyslogListener.o \
	$(OBJDIR)/ServerSocket.o \
	$(OBJDIR)/ServerSocketImpl.o \
	$(OBJDIR)/SMTPClientSession.o \
	$(OBJDIR)/Socket.o \
	$(OBJDIR)/SocketAddress.o \
	$(OBJDIR)/SocketImpl.o \
	$(OBJDIR)/SocketNotification.o \
	$(OBJDIR)/SocketNotifier.o \
	$(OBJDIR)/SocketReactor.o \
	$(OBJDIR)/SocketStream.o \
	$(OBJDIR)/StreamSocket.o \
	$(OBJDIR)/StreamSocketImpl.o \
	$(OBJDIR)/StringPartSource.o \
	$(OBJDIR)/TCPServer.o \
	$(OBJDIR)/TCPServerConnection.o \
	$(OBJDIR)/TCPServerConnectionFactory.o \
	$(OBJDIR)/TCPServerDispatcher.o \
	$(OBJDIR)/TCPServerParams.o \
	$(OBJDIR)/WebSocket.o \
	$(OBJDIR)/WebSocketImpl.o \

RESOURCES := \

SHELLTYPE := msdos
ifeq (,$(ComSpec)$(COMSPEC))
  SHELLTYPE := posix
endif
ifeq (/bin,$(findstring /bin,$(SHELL)))
  SHELLTYPE := posix
endif

.PHONY: clean prebuild prelink

all: $(TARGETDIR) $(OBJDIR) prebuild prelink $(TARGET)
	@:

$(TARGET): $(GCH) $(OBJECTS) $(LDDEPS) $(RESOURCES)
	@echo Linking PocoNet
	$(SILENT) $(LINKCMD)
	$(POSTBUILDCMDS)

$(TARGETDIR):
	@echo Creating $(TARGETDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(TARGETDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(TARGETDIR))
endif

$(OBJDIR):
	@echo Creating $(OBJDIR)
ifeq (posix,$(SHELLTYPE))
	$(SILENT) mkdir -p $(OBJDIR)
else
	$(SILENT) mkdir $(subst /,\\,$(OBJDIR))
endif

clean:
	@echo Cleaning PocoNet
ifeq (posix,$(SHELLTYPE))
	$(SILENT) rm -f  $(TARGET)
	$(SILENT) rm -rf $(OBJDIR)
else
	$(SILENT) if exist $(subst /,\\,$(TARGET)) del $(subst /,\\,$(TARGET))
	$(SILENT) if exist $(subst /,\\,$(OBJDIR)) rmdir /s /q $(subst /,\\,$(OBJDIR))
endif

prebuild:
	$(PREBUILDCMDS)

prelink:
	$(PRELINKCMDS)

ifneq (,$(PCH))
$(GCH): $(PCH)
	@echo $(notdir $<)
	-$(SILENT) cp $< $(OBJDIR)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
endif

$(OBJDIR)/AbstractHTTPRequestHandler.o: src/AbstractHTTPRequestHandler.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DatagramSocket.o: src/DatagramSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DatagramSocketImpl.o: src/DatagramSocketImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DialogSocket.o: src/DialogSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/DNS.o: src/DNS.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FilePartSource.o: src/FilePartSource.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FTPClientSession.o: src/FTPClientSession.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/FTPStreamFactory.o: src/FTPStreamFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HostEntry.o: src/HostEntry.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTMLForm.o: src/HTMLForm.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPAuthenticationParams.o: src/HTTPAuthenticationParams.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPBasicCredentials.o: src/HTTPBasicCredentials.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPBufferAllocator.o: src/HTTPBufferAllocator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPChunkedStream.o: src/HTTPChunkedStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPClientSession.o: src/HTTPClientSession.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPCookie.o: src/HTTPCookie.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPCredentials.o: src/HTTPCredentials.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPDigestCredentials.o: src/HTTPDigestCredentials.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPFixedLengthStream.o: src/HTTPFixedLengthStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPHeaderStream.o: src/HTTPHeaderStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPIOStream.o: src/HTTPIOStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPMessage.o: src/HTTPMessage.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPRequest.o: src/HTTPRequest.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPRequestHandler.o: src/HTTPRequestHandler.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPRequestHandlerFactory.o: src/HTTPRequestHandlerFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPResponse.o: src/HTTPResponse.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPServer.o: src/HTTPServer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPServerConnection.o: src/HTTPServerConnection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPServerConnectionFactory.o: src/HTTPServerConnectionFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPServerParams.o: src/HTTPServerParams.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPServerRequest.o: src/HTTPServerRequest.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPServerRequestImpl.o: src/HTTPServerRequestImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPServerResponse.o: src/HTTPServerResponse.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPServerResponseImpl.o: src/HTTPServerResponseImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPServerSession.o: src/HTTPServerSession.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPSession.o: src/HTTPSession.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPSessionFactory.o: src/HTTPSessionFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPSessionInstantiator.o: src/HTTPSessionInstantiator.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPStream.o: src/HTTPStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/HTTPStreamFactory.o: src/HTTPStreamFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ICMPClient.o: src/ICMPClient.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ICMPEventArgs.o: src/ICMPEventArgs.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ICMPPacket.o: src/ICMPPacket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ICMPPacketImpl.o: src/ICMPPacketImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ICMPSocket.o: src/ICMPSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ICMPSocketImpl.o: src/ICMPSocketImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ICMPv4PacketImpl.o: src/ICMPv4PacketImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/IPAddress.o: src/IPAddress.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MailMessage.o: src/MailMessage.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MailRecipient.o: src/MailRecipient.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MailStream.o: src/MailStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MediaType.o: src/MediaType.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MessageHeader.o: src/MessageHeader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MulticastSocket.o: src/MulticastSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MultipartReader.o: src/MultipartReader.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/MultipartWriter.o: src/MultipartWriter.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/NameValueCollection.o: src/NameValueCollection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/NetException.o: src/NetException.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/NetworkInterface.o: src/NetworkInterface.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/NullPartHandler.o: src/NullPartHandler.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PartHandler.o: src/PartHandler.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/PartSource.o: src/PartSource.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/POP3ClientSession.o: src/POP3ClientSession.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QuotedPrintableDecoder.o: src/QuotedPrintableDecoder.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/QuotedPrintableEncoder.o: src/QuotedPrintableEncoder.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RawSocket.o: src/RawSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RawSocketImpl.o: src/RawSocketImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RemoteSyslogChannel.o: src/RemoteSyslogChannel.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/RemoteSyslogListener.o: src/RemoteSyslogListener.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ServerSocket.o: src/ServerSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/ServerSocketImpl.o: src/ServerSocketImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SMTPClientSession.o: src/SMTPClientSession.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/Socket.o: src/Socket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SocketAddress.o: src/SocketAddress.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SocketImpl.o: src/SocketImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SocketNotification.o: src/SocketNotification.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SocketNotifier.o: src/SocketNotifier.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SocketReactor.o: src/SocketReactor.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/SocketStream.o: src/SocketStream.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StreamSocket.o: src/StreamSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StreamSocketImpl.o: src/StreamSocketImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/StringPartSource.o: src/StringPartSource.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TCPServer.o: src/TCPServer.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TCPServerConnection.o: src/TCPServerConnection.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TCPServerConnectionFactory.o: src/TCPServerConnectionFactory.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TCPServerDispatcher.o: src/TCPServerDispatcher.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/TCPServerParams.o: src/TCPServerParams.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/WebSocket.o: src/WebSocket.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"
$(OBJDIR)/WebSocketImpl.o: src/WebSocketImpl.cpp
	@echo $(notdir $<)
	$(SILENT) $(CXX) $(CXXFLAGS) -o "$@" -c "$<"

-include $(OBJECTS:%.o=%.d)
